* Crescita Personale

** Rilassamento
   Sto cercando di trovare modi per acquisiree mantenere il controllo emotivo.
   non credo sia proprio controllo quanto un uno stato di "know-how" che ti evita il panico
  
   
*** I problemi sono vari
   - l'effetto sopresa
   - l'emotivo che sale
   - situazioni mai uguali
   - l'abitudine errata ad andare "in panico"

*** Possibili Soluzioni:
    max ha proposto alcune tecniche di respirazione prese da QI GONG
    
    io credo che bisogna entrare nell'ottica del *ce la posso fare* in qualunque occasione
    le tecniche di respirazioni servono a tamponare l'agitazionema la soluzione è entare
    nell'ottica che nsi riesca a fare tutto come un vettore che punta in avanti cmq e cerca una soluzione.
**** la mia esperienzaù
     

**** come?
     - pratica pratica pratica
     - provare a farlo in un reale
     - prendere confidenza con la calma
**** ci sto riuscendo?
     - nei casi di alto stress ho ancora problemi a gestire
     - migliorato lo status di quiete in fase comoda
     - migliorata la consapevolezza in fase "stress"
     

** Gestione pensieri
   ho notato che in una giornata *uggiosa* è molto piu facile essere inclini ad uno stato risolutivo
   e credo che  sia bilaterale (giornata/status)
   
   poniamo per esempio che ad un certo punto un problema sorga, fermiamo il tempo, l'emozione negativa sta per sorgere:
   in realta  si arriva ad un bivio: andare in panico o affrontare il problema.
   
  - il panico è gratuito per cui è molto piu facile scegliere quella opzione
  - lo stato risolutivo richiede un prezzo: energia, tempo e autostima
  - le prime sono facilmente ottenibili, l'autostima va gestita
  - io sono arrivatio qui

** Formalizzare

   Non sono sicuro cosa voglia dire formalizzare, parafrasando wikipedia formalizzare significa rendere ufficiale un *qualcosa*
   
***  Uffializzare un Pensiero
   
   Sto cercando di capirne il senso, speso lo si fa in automatico, confermi un idea  nel momento in cui  /la credi reale/,
   quando lo =rendi=  reale. 
   
   
** Attuare
  
*** La variabile dell'inconscio
   
   Come in una variabile qualsiasi del nostro amato Java, se la cosidetta ha un valore non ne può aveere un altro.
   Formalizzare in anticipo percio un pensiero potrebbe equivalere a *dare un valore alla variabile* cosicchè  si disabiliti
   il riempimento automatico causato dall'inconscio. 
   

 
   


* Git

** commands

 
*** git init
    crea una repository locale

*** git remote add origin <link>
    collega la repositoruy locale al Git in rete

*** git add culo.org
    prepara un file all'upload

*** git commit -all
    convalida il file pronto perl'upload
    -m <messaggio> lascia una nota

*** git push origin master
    carica file su Git su master

*** git checkout - b <nome>
    crea nuovo branch alternativo al master

*** git checkout master
    ritorna a master

*** branch -d <nome>
    cancella branch

*** git push origin <branch>
    carica branch su Git


* Links

- [[https://github.com/peynfx/Studio/blob/master/Note.org][Repository]] --- c-c c-l to make a link

- [[file:Sayhello.java][Java example]] ---open java file below

- you can link also mails and other files and other orgs!
- yeah
  

* Outliner

 - use * and space to make an outliner

 - use more ** to create a subtree

 - use shift+tab to extend or close outliners

  text text text!
   * +dfv+ (+)
   * *bold*
   * /italic/
   * =text2=
  

** outliner 2 
text
 ** ore
 * more items
   + lol
   + lol
   + met+ret(invio) add items
   + more items

     - bullet

     - bullet

     - bullet



* Tables
    

| data1 | data2 | data3 |
|-------+-------+-------|

- use |- and tab to fill the tab

| numeri | data |
|--------+------|
|     12 | ciao |
|     13 | ola  |
|--------+------|


               
- use meta+arrows to rearrange

  
* Export formats

*C-c C-e*



  
* META DATAS: 

#+TITLE: Lo Zen del Programmatore
#+OPTIONS: toc:nil


* Source Code
 
#

#+BEGIN_SRC java

import java.util.*;

public class Ciao{

public static void main(String[] args){

}

}

#+END_SRC


#+RESULTS:
